name: Telegram userbot

on:
  push:
  workflow_dispatch:
    
env:
  GitHubMail: "${{ secrets.GHMAIL }}"
  GitHubName: "rahulkhatri137" 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Set Git Configs & Secrets
         run: |
           git config --global user.email "${GitHubMail}"
           git config --global user.name "${GitHubName}"
           echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           sudo apt install expect -y

       - name: cloning repo
         continue-on-error: false
         run: |
           git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/rahulkhatri137/Ultroid bot

       - name: Running Bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd bot
           touch .env
           nano .env
           echo "API_ID=" ;
