name: Telegram userbot

on:
  push:
  workflow_dispatch:
    
env:
  GitHubMail: "${{ secrets.GHMAIL }}"
  GitHubName: "rahulkhatri137" 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: Set Git Configs & Secrets
         run: |
           git config --global user.email "${GitHubMail}"
           git config --global user.name "${GitHubName}"
           sudo apt install expect -y

       - name: cloning repo
         continue-on-error: false
         run: |
           expect -c " 
           spawn git clone https://github.com/rahulkhatri137/ultroi bot
           expect \"Username\"        
           send \"${{ secrets.GHUSER }}\r\"
           expect \"Password\"        
           send \"${{ secrets.GHPASS }}\r\"
           set timeout -5
           catch wait result
           interact"
       - name: Running Bot
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd bot
           pip3 install -U -r requirements.txt
           bash resources/startup/startup.sh
       
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/rahulkhatri137/ult-wf loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
